/*
 *  Copyright 2025 Better Orange IR & HV AG
 *
 *  Licensed under the Meetingbase License (the "License");
 *  Vou may not use this file except in compliance with the License.
 *  You may obtain a copy of the License in the root directory (MEETINGBASE_LICENSE).
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package de.meetingapps.meetingportal.meetComKonst;

public class KonstAuftragArt {

    public final static int UNBEKANNT = 0;
    public final static int ANBINDUNG_AKTIENREGISTER_AENDERN_NEWSLETTER = 1;
    public final static int ANBINDUNG_AKTIENREGISTER_AENDERN_MEINEDATEN_ANSCHRIFT = 2;
//    public final static int ANBINDUNG_AKTIENREGISTER_AENDERN_MEINEDATEN_KONTAKTDATEN = 3;
    public final static int ANBINDUNG_AKTIENREGISTER_AENDERN_MEINEDATEN_GEBURTSDATUM = 4;
    public final static int ANBINDUNG_AKTIENREGISTER_AENDERN_MEINEDATEN_STEUERID = 5;
    public final static int ANBINDUNG_AKTIENREGISTER_AENDERN_MEINEDATEN_BANKVERBINDUNG = 6;
    
    public final static int ANBINDUNG_AKTIENREGISTER_AENDERN_MEINEDATEN_TELEFON1 = 7;
    public final static int ANBINDUNG_AKTIENREGISTER_AENDERN_MEINEDATEN_TELEFON2 = 8;
    public final static int ANBINDUNG_AKTIENREGISTER_AENDERN_MEINEDATEN_TELEFON3 = 9;
    public final static int ANBINDUNG_AKTIENREGISTER_AENDERN_MEINEDATEN_TELEFON4 = 11;
    public final static int ANBINDUNG_AKTIENREGISTER_AENDERN_MEINEDATEN_EMAIL = 10;
    
    
//  public final static int ANBINDUNG_AKTIENREGISTER_ANTRAG_BETEILIGUNGSERHOEHUNG = 12;
    public final static int ANBINDUNG_AKTIENREGISTER_ANTRAG_BETEILIGUNGSERHOEHUNG_ZEICHNUNG_OHNE_AUFFUELLBETRAG = 13;
    public final static int ANBINDUNG_AKTIENREGISTER_ANTRAG_BETEILIGUNGSERHOEHUNG_ZEICHNUNG_UND_AUFFUELLBETRAG = 14;
    public final static int ANBINDUNG_AKTIENREGISTER_ANTRAG_BETEILIGUNGSERHOEHUNG_OHNE_ZEICHNUNG_MIT_AUFFUELLBETRAG = 15;
    public final static int ANBINDUNG_AKTIENREGISTER_ANTRAG_BETEILIGUNGSERHOEHUNG_ZEICHNUNG_OHNE_AUFFUELLBETRAG_TEXTFORM = 16;

    
    public static String getText(int pAuftragArt) {
        switch (pAuftragArt) {
        case ANBINDUNG_AKTIENREGISTER_AENDERN_NEWSLETTER:return "NEWSLETTER";
        case ANBINDUNG_AKTIENREGISTER_AENDERN_MEINEDATEN_ANSCHRIFT:return "MEINEDATEN_ANSCHRIFT";
        case ANBINDUNG_AKTIENREGISTER_AENDERN_MEINEDATEN_GEBURTSDATUM:return "MEINEDATEN_GEBURTSDATUM";
        case ANBINDUNG_AKTIENREGISTER_AENDERN_MEINEDATEN_STEUERID:return "MEINEDATEN_STEUERID";
        case ANBINDUNG_AKTIENREGISTER_AENDERN_MEINEDATEN_BANKVERBINDUNG:return "MEINEDATEN_BANKVERBINDUNG";
        
        case ANBINDUNG_AKTIENREGISTER_AENDERN_MEINEDATEN_TELEFON1:return "MEINEDATEN_TELEFON1";
        case ANBINDUNG_AKTIENREGISTER_AENDERN_MEINEDATEN_TELEFON2:return "MEINEDATEN_TELEFON2";
        case ANBINDUNG_AKTIENREGISTER_AENDERN_MEINEDATEN_TELEFON3:return "MEINEDATEN_TELEFON3r";
        case ANBINDUNG_AKTIENREGISTER_AENDERN_MEINEDATEN_TELEFON4:return "MEINEDATEN_TELEFON4";
        case ANBINDUNG_AKTIENREGISTER_AENDERN_MEINEDATEN_EMAIL:return "MEINEDATEN_EMAIL";
        
//        case ANBINDUNG_AKTIENREGISTER_ANTRAG_BETEILIGUNGSERHOEHUNG:return "ANTRAG_BETEILIGUNGSERHOEHUNG";
        case ANBINDUNG_AKTIENREGISTER_ANTRAG_BETEILIGUNGSERHOEHUNG_ZEICHNUNG_OHNE_AUFFUELLBETRAG:return "ANBINDUNG_AKTIENREGISTER_ANTRAG_BETEILIGUNGSERHOEHUNG_ZEICHNUNG_OHNE_AUFFUELLBETRAG";
        case ANBINDUNG_AKTIENREGISTER_ANTRAG_BETEILIGUNGSERHOEHUNG_ZEICHNUNG_UND_AUFFUELLBETRAG:return "ANBINDUNG_AKTIENREGISTER_ANTRAG_BETEILIGUNGSERHOEHUNG_ZEICHNUNG_UND_AUFFUELLBETRAG";
        case ANBINDUNG_AKTIENREGISTER_ANTRAG_BETEILIGUNGSERHOEHUNG_OHNE_ZEICHNUNG_MIT_AUFFUELLBETRAG:return "ANBINDUNG_AKTIENREGISTER_ANTRAG_BETEILIGUNGSERHOEHUNG_OHNE_ZEICHNUNG_MIT_AUFFUELLBETRAG";
        case ANBINDUNG_AKTIENREGISTER_ANTRAG_BETEILIGUNGSERHOEHUNG_ZEICHNUNG_OHNE_AUFFUELLBETRAG_TEXTFORM:return "ANBINDUNG_AKTIENREGISTER_ANTRAG_BETEILIGUNGSERHOEHUNG_ZEICHNUNG_OHNE_AUFFUELLBETRAG_TEXTFORM";
        }
        
        return "";
    }
}
