/*
 *  Copyright 2025 Better Orange IR & HV AG
 *
 *  Licensed under the Meetingbase License (the "License");
 *  Vou may not use this file except in compliance with the License.
 *  You may obtain a copy of the License in the root directory (MEETINGBASE_LICENSE).
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package de.meetingapps.meetingportal.meetComHVParam;

public class KonstParameter {

    public static int PRUEFBIT_MODULE_KONFIGURIERBAR__AKTIONAERSPORTAL=1;
    public static int PRUEFBIT_MODULE_KONFIGURIERBAR__BRIEFWAHL=2;
    public static int PRUEFBIT_MODULE_KONFIGURIERBAR__WEISUNGEN_SCHNITTSTELLE_EXTERNES_SYSTEM=4;
    public static int PRUEFBIT_MODULE_KONFIGURIERBAR__EMITTENTENPORTAL=8;
    public static int PRUEFBIT_MODULE_KONFIGURIERBAR__REGISTERANBINDUNG=16;
    public static int PRUEFBIT_MODULE_KONFIGURIERBAR__ELEKTRONISCHES_TEILNEHMERVERZEICHNIS=32;
    public static int PRUEFBIT_MODULE_KONFIGURIERBAR__ELEKTRONISCHE_WEISUNGSERFASSUNG_HV=64;
    public static int PRUEFBIT_MODULE_KONFIGURIERBAR__TABLET_ABSTIMMUNG=128;
    public static int PRUEFBIT_MODULE_KONFIGURIERBAR__SCANNER_ABSTIMMUNG=256;
    public static int PRUEFBIT_MODULE_KONFIGURIERBAR__HV_APP=512;
    public static int PRUEFBIT_MODULE_KONFIGURIERBAR__HV_APP_ABSTIMMUNG=1024;
    public static int PRUEFBIT_MODULE_KONFIGURIERBAR__HV_APP_HV_FUNKTIONEN=2048;
    public static int PRUEFBIT_MODULE_KONFIGURIERBAR__ELEKTRONISCHER_STIMMBLOCK=4096;
    public static int PRUEFBIT_MODULE_KONFIGURIERBAR__ONLINE_TEILNAHME=8192;
    public static int PRUEFBIT_MODULE_KONFIGURIERBAR__ENGLISCHE_AGENDA=16384;
    public static int PRUEFBIT_MODULE_KONFIGURIERBAR__MEHRERE_GATTUNGEN=32768;
    
    
    /**tbl_emittent*/
    public static int MODULE_KONFIGURIERBAR__AKTIONAERSPORTAL=1;
    public static int MODULE_KONFIGURIERBAR__BRIEFWAHL=2;
    public static int MODULE_KONFIGURIERBAR__WEISUNGEN_SCHNITTSTELLE_EXTERNES_SYSTEM=3;
    
    /**tbl_emittent*/
    public static int MODULE_KONFIGURIERBAR__EMITTENTENPORTAL=4;
    
    /**tbl_emittent*/
    public static int MODULE_KONFIGURIERBAR__REGISTERANBINDUNG=5;
    public static int MODULE_KONFIGURIERBAR__ELEKTRONISCHES_TEILNEHMERVERZEICHNIS=6;
    public static int MODULE_KONFIGURIERBAR__ELEKTRONISCHE_WEISUNGSERFASSUNG_HV=7;
    public static int MODULE_KONFIGURIERBAR__TABLET_ABSTIMMUNG=8;
    public static int MODULE_KONFIGURIERBAR__SCANNER_ABSTIMMUNG=9;

    /**tbl_emittent*/
    public static int MODULE_KONFIGURIERBAR__HV_APP=10;
    public static int MODULE_KONFIGURIERBAR__HV_APP_ABSTIMMUNG=11;
    public static int MODULE_KONFIGURIERBAR__HV_APP_HV_FUNKTIONEN=12;
    public static int MODULE_KONFIGURIERBAR__ELEKTRONISCHER_STIMMBLOCK=13;
    public static int MODULE_KONFIGURIERBAR__ONLINE_TEILNAHME=14;
    public static int MODULE_KONFIGURIERBAR__HV_FORM=15;
    public static int MODULE_KONFIGURIERBAR__ENGLISCHE_AGENDA=16;
    public static int MODULE_KONFIGURIERBAR__MEHRERE_GATTUNGEN=17;
//    public static int MODULE_KONFIGURIERBAR__=;
    
    public static int BASIS__INHABERAKTIEN_AKTIV=101;
    public static int BASIS__NAMENSAKTIEN_AKTIV=102;
    public static int BASIS__INVESTOREN_SIND=103;

    public static int BASIS__GATTUNG_AKTIV_1=111;
    public static int BASIS__GATTUNG_AKTIV_2=112;
    public static int BASIS__GATTUNG_AKTIV_3=113;
    public static int BASIS__GATTUNG_AKTIV_4=114;
    public static int BASIS__GATTUNG_AKTIV_5=115;
    
    public static int BASIS__GATTUNG_BEZEICHNUNG_1=116;
    public static int BASIS__GATTUNG_BEZEICHNUNG_2=117;
    public static int BASIS__GATTUNG_BEZEICHNUNG_3=118;
    public static int BASIS__GATTUNG_BEZEICHNUNG_4=119;
    public static int BASIS__GATTUNG_BEZEICHNUNG_5=120;
    
    public static int BASIS__GATTUNG_BEZEICHNUNG_EN_1=121;
    public static int BASIS__GATTUNG_BEZEICHNUNG_EN_2=122;
    public static int BASIS__GATTUNG_BEZEICHNUNG_EN_3=123;
    public static int BASIS__GATTUNG_BEZEICHNUNG_EN_4=124;
    public static int BASIS__GATTUNG_BEZEICHNUNG_EN_5=125;
   
    public static int BASIS__GATTUNG_BEZEICHNUNG_KURZ_1=126;
    public static int BASIS__GATTUNG_BEZEICHNUNG_KURZ_2=127;
    public static int BASIS__GATTUNG_BEZEICHNUNG_KURZ_3=128;
    public static int BASIS__GATTUNG_BEZEICHNUNG_KURZ_4=129;
    public static int BASIS__GATTUNG_BEZEICHNUNG_KURZ_5=130;

    public static int BASIS__GRUNDKAPITAL_STUECK_1=131;
    public static int BASIS__GRUNDKAPITAL_STUECK_2=132;
    public static int BASIS__GRUNDKAPITAL_STUECK_3=133;
    public static int BASIS__GRUNDKAPITAL_STUECK_4=134;
    public static int BASIS__GRUNDKAPITAL_STUECK_5=135;

    public static int BASIS__GRUNDKAPITAL_VERMINDERT_STUECK_1=136;
    public static int BASIS__GRUNDKAPITAL_VERMINDERT_STUECK_2=137;
    public static int BASIS__GRUNDKAPITAL_VERMINDERT_STUECK_3=138;
    public static int BASIS__GRUNDKAPITAL_VERMINDERT_STUECK_4=139;
    public static int BASIS__GRUNDKAPITAL_VERMINDERT_STUECK_5=140;
    
    public static int BASIS__GRUNDKAPITAL_EIGENE_AKTIEN_STUECK_1=141;
    public static int BASIS__GRUNDKAPITAL_EIGENE_AKTIEN_STUECK_2=142;
    public static int BASIS__GRUNDKAPITAL_EIGENE_AKTIEN_STUECK_3=143;
    public static int BASIS__GRUNDKAPITAL_EIGENE_AKTIEN_STUECK_4=144;
    public static int BASIS__GRUNDKAPITAL_EIGENE_AKTIEN_STUECK_5=145;

    public static int BASIS__WERT_EINER_AKTIE_1=146;
    public static int BASIS__WERT_EINER_AKTIE_2=147;
    public static int BASIS__WERT_EINER_AKTIE_3=148;
    public static int BASIS__WERT_EINER_AKTIE_4=149;
    public static int BASIS__WERT_EINER_AKTIE_5=150;
    
    public static int BASIS__ANZAHL_NACHKOMMASTELLEN_KAPITAL_1=151;
    public static int BASIS__ANZAHL_NACHKOMMASTELLEN_KAPITAL_2=152;
    public static int BASIS__ANZAHL_NACHKOMMASTELLEN_KAPITAL_3=153;
    public static int BASIS__ANZAHL_NACHKOMMASTELLEN_KAPITAL_4=154;
    public static int BASIS__ANZAHL_NACHKOMMASTELLEN_KAPITAL_5=155;
 
    public static int BASIS__EINTRITTSKARTE_NEU_VERGEBEN_1=156;
    public static int BASIS__EINTRITTSKARTE_NEU_VERGEBEN_2=157;
    public static int BASIS__EINTRITTSKARTE_NEU_VERGEBEN_3=158;
    public static int BASIS__EINTRITTSKARTE_NEU_VERGEBEN_4=159;
    public static int BASIS__EINTRITTSKARTE_NEU_VERGEBEN_5=160;

    public static int BASIS__ZUGANG_MOEGLICH_1=161;
    public static int BASIS__ZUGANG_MOEGLICH_2=162;
    public static int BASIS__ZUGANG_MOEGLICH_3=163;
    public static int BASIS__ZUGANG_MOEGLICH_4=164;
    public static int BASIS__ZUGANG_MOEGLICH_5=165;
   
    public static int BASIS__ZWEITER_MANDANT_NR=166;
    public static int BASIS__ZWEITER_MANDANT_HV_JAHR=167;
    public static int BASIS__ZWEITER_MANDANT_HV_NUMMER=168;
    public static int BASIS__ZWEITER_MANDANT_DATENBEREICH=169;

    public static int BASIS__LAENGE_AKTIONAERSNUMMER=170;
    public static int BASIS__OHNE_NULL_AKTIONAERSNUMMER=171;
    public static int BASIS__EINDEUTIGE_HV_KENNUNG=172;
    
    public static int BASIS__ISIN_1=176;
    public static int BASIS__ISIN_2=177;
    public static int BASIS__ISIN_3=178;
    public static int BASIS__ISIN_4=179;
    public static int BASIS__ISIN_5=180;
    
    public static int BASIS__MAIL_CONSULTANT=181;
    public static int BASIS__EK_SEITENZAHL=182;
    public static int BASIS__EK_FORMULAR_GETRENNT_JE_VERSANDWEG=183;
    
    public static int BASIS__PROFIL_KLASSE=184;
    
    public static int BASIS__SEND_MAIL_ADRESSE=185;
    public static int BASIS__WEBHOOK_ENDPOINT_URL=186;
    public static int BASIS__WEBHOOK_ENDPOINT_USERNAME=187;
    public static int BASIS__WEBHOOK_ENDPOINT_PASSWORT=188;
    
    /**tbl_emittent*/
    public static int BASIS__DATENBESTAND_IST_PRODUKTIV=189;

    public static int BASIS__HOECHSTSTIMMRECHT_HACK_AKTIV=190;
    public static int BASIS__STIMMEN_BEI_PRAESENZ_REDUZIEREN_UM_STIMMEN=191;

    public static int NUMMERNFORMEN__IDENT=501;
    public static int NUMMERNFORMEN__IGNORIERE_KARTENART=502;
    
    public static int PRUEFZAHLEN__IDENTIFIKATIONS_NUMMER=503;
    public static int PRUEFZAHLEN__DREISTELLIGE_KONTROLLZAHL=504;
    public static int PRUEFZAHLEN__ZWEISTELLIGE_KONTROLLZAHL=505;
    public static int PRUEFZAHLEN__EINSTELLIGE_KONTROLLZAHL=506;



    
    public static int AKKREDITIERUNG_GAESTE_KARTEN_HABEN_WIEDERZUGANG_ABGANGS_CODE=1001;
    public static int AKKREDITIERUNG_EINTRITTSKARTE_WIRD_AUCH_FUER_ABGANG_WIEDERZUGANG_VERWENDET=1002;
    public static int AKKREDITIERUNG_EINTRITTSKARTE_WIRD_STIMMKARTE=1003;
    public static int AKKREDITIERUNG_LABEL_AUCH_FUER_APP_IDENT=1004;
    public static int AKKREDITIERUNG_POSITION_VERTRETERNAME=1005;
    public static int AKKREDITIERUNG_DELAY_ART=1006;
    public static int AKKREDITIERUNG_BEI_ZUGANG_STORNIEREN_AUS_SAMMEL_AUTOMATISCH=1007;
    public static int AKKREDITIERUNG_BEI_ZUGANG_SELBST_VERTRETER_IGNORIEREN_ZULAESSIG=1008;
    public static int AKKREDITIERUNG_UNGEPRUEFTE_KARTEN_NICHT_BUCHEN=1009;

    /*XXX Noch nicht in Oberflächen*/
    public static int AKKREDITIERUNG_P_PRAESENZ_STORNIEREN_AUS_SAMMELKARTE_ZWINGEND_0=1010;
    public static int AKKREDITIERUNG_P_PRAESENZ_STORNIEREN_AUS_SAMMELKARTE_ZWINGEND_1_KIAV=1011;
    public static int AKKREDITIERUNG_P_PRAESENZ_STORNIEREN_AUS_SAMMELKARTE_ZWINGEND_2_SRV=1012;
    public static int AKKREDITIERUNG_P_PRAESENZ_STORNIEREN_AUS_SAMMELKARTE_ZWINGEND_3_ORGANISATORISCH=1013;
    public static int AKKREDITIERUNG_P_PRAESENZ_STORNIEREN_AUS_SAMMELKARTE_ZWINGEND_4_BRIEFWAHL=1014;
    public static int AKKREDITIERUNG_P_PRAESENZ_STORNIEREN_AUS_SAMMELKARTE_ZWINGEND_5_DAUERVOLLMACHT=1015;
    
    public static int AKKREDITIERUNG_AUSZUGEBENDE_STIMMKARTEN_IN_MELDUNG_ANZEIGEN=1016;
    
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_AKTIV_G1_1=1017;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_AKTIV_G1_2=1018;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_AKTIV_G1_3=1019;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_AKTIV_G1_4=1020;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_AKTIV_G1_5=1021;
            
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_AKTIV_G2_1=1022;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_AKTIV_G2_2=1023;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_AKTIV_G2_3=1024;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_AKTIV_G2_4=1025;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_AKTIV_G2_5=1026;
    
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_AKTIV_G3_1=1027;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_AKTIV_G3_2=1028;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_AKTIV_G3_3=1029;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_AKTIV_G3_4=1030;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_AKTIV_G3_5=1031;
    
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_AKTIV_G4_1=1032;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_AKTIV_G4_2=1033;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_AKTIV_G4_3=1034;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_AKTIV_G4_4=1035;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_AKTIV_G4_5=1036;
    
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_AKTIV_G5_1=1037;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_AKTIV_G5_2=1038;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_AKTIV_G5_3=1039;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_AKTIV_G5_4=1040;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_AKTIV_G5_5=1041;

    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_G1_1=1042;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_G1_2=1043;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_G1_3=1044;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_G1_4=1045;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_G1_5=1046;
            
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_G2_1=1047;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_G2_2=1048;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_G2_3=1049;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_G2_4=1050;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_G2_5=1051;
    
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_G3_1=1052;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_G3_2=1053;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_G3_3=1054;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_G3_4=1055;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_G3_5=1056;
    
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_G4_1=1057;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_G4_2=1058;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_G4_3=1059;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_G4_4=1060;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_G4_5=1061;
    
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_G5_1=1062;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_G5_2=1063;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_G5_3=1064;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_G5_4=1065;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_G5_5=1066;

    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_APP_GATTUNG_G1_1=1067;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_APP_GATTUNG_G1_2=1068;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_APP_GATTUNG_G1_3=1069;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_APP_GATTUNG_G1_4=1070;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_APP_GATTUNG_G1_5=1071;
            
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_APP_GATTUNG_G2_1=1072;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_APP_GATTUNG_G2_2=1073;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_APP_GATTUNG_G2_3=1074;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_APP_GATTUNG_G2_4=1075;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_APP_GATTUNG_G2_5=1076;
    
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_APP_GATTUNG_G3_1=1077;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_APP_GATTUNG_G3_2=1078;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_APP_GATTUNG_G3_3=1079;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_APP_GATTUNG_G3_4=1080;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_APP_GATTUNG_G3_5=1081;
    
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_APP_GATTUNG_G4_1=1082;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_APP_GATTUNG_G4_2=1083;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_APP_GATTUNG_G4_3=1084;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_APP_GATTUNG_G4_4=1085;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_APP_GATTUNG_G4_5=1086;
    
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_APP_GATTUNG_G5_1=1087;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_APP_GATTUNG_G5_2=1088;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_APP_GATTUNG_G5_3=1089;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_APP_GATTUNG_G5_4=1090;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_APP_GATTUNG_G5_5=1091;

    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_TEXT_G1_1=1092;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_TEXT_G1_2=1093;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_TEXT_G1_3=1094;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_TEXT_G1_4=1095;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_TEXT_G1_5=1096;
           
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_TEXT_G2_1=1097;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_TEXT_G2_2=1098;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_TEXT_G2_3=1099;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_TEXT_G2_4=1100;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_TEXT_G2_5=1101;
    
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_TEXT_G3_1=1102;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_TEXT_G3_2=1103;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_TEXT_G3_3=1104;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_TEXT_G3_4=1105;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_TEXT_G3_5=1106;
    
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_TEXT_G4_1=1107;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_TEXT_G4_2=1108;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_TEXT_G4_3=1109;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_TEXT_G4_4=1110;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_TEXT_G4_5=1111;
    
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_TEXT_G5_1=1112;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_TEXT_G5_2=1113;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_TEXT_G5_3=1114;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_TEXT_G5_4=1115;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTEN_ZUORDNEN_GATTUNG_TEXT_G5_5=1116;

    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_FORMULARNUMMER_G1_1=1117;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_FORMULARNUMMER_G1_2=1118;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_FORMULARNUMMER_G1_3=1119;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_FORMULARNUMMER_G1_4=1120;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_FORMULARNUMMER_G1_5=1121;
            
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_FORMULARNUMMER_G2_1=1122;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_FORMULARNUMMER_G2_2=1123;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_FORMULARNUMMER_G2_3=1124;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_FORMULARNUMMER_G2_4=1125;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_FORMULARNUMMER_G2_5=1126;
    
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_FORMULARNUMMER_G3_1=1127;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_FORMULARNUMMER_G3_2=1128;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_FORMULARNUMMER_G3_3=1129;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_FORMULARNUMMER_G3_4=1130;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_FORMULARNUMMER_G3_5=1131;
    
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_FORMULARNUMMER_G4_1=1132;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_FORMULARNUMMER_G4_2=1133;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_FORMULARNUMMER_G4_3=1134;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_FORMULARNUMMER_G4_4=1135;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_FORMULARNUMMER_G4_5=1136;
    
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_FORMULARNUMMER_G5_1=1137;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_FORMULARNUMMER_G5_2=1138;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_FORMULARNUMMER_G5_3=1139;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_FORMULARNUMMER_G5_4=1140;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_FORMULARNUMMER_G5_5=1141;
   
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_TAUSCH_BELIEBIG_G1_1=1142;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_TAUSCH_BELIEBIG_G1_2=1143;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_TAUSCH_BELIEBIG_G1_3=1144;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_TAUSCH_BELIEBIG_G1_4=1145;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_TAUSCH_BELIEBIG_G1_5=1146;
            
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_TAUSCH_BELIEBIG_G2_1=1147;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_TAUSCH_BELIEBIG_G2_2=1148;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_TAUSCH_BELIEBIG_G2_3=1149;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_TAUSCH_BELIEBIG_G2_4=1150;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_TAUSCH_BELIEBIG_G2_5=1151;
    
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_TAUSCH_BELIEBIG_G3_1=1152;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_TAUSCH_BELIEBIG_G3_2=1153;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_TAUSCH_BELIEBIG_G3_3=1154;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_TAUSCH_BELIEBIG_G3_4=1155;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_TAUSCH_BELIEBIG_G3_5=1156;
    
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_TAUSCH_BELIEBIG_G4_1=1157;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_TAUSCH_BELIEBIG_G4_2=1158;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_TAUSCH_BELIEBIG_G4_3=1159;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_TAUSCH_BELIEBIG_G4_4=1160;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_TAUSCH_BELIEBIG_G4_5=1161;
    
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_TAUSCH_BELIEBIG_G5_1=1162;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_TAUSCH_BELIEBIG_G5_2=1163;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_TAUSCH_BELIEBIG_G5_3=1164;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_TAUSCH_BELIEBIG_G5_4=1165;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_TAUSCH_BELIEBIG_G5_5=1166;
   
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_NACHDRUCK_SERVICE_DESK_G1_1=1167;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_NACHDRUCK_SERVICE_DESK_G1_2=1168;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_NACHDRUCK_SERVICE_DESK_G1_3=1169;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_NACHDRUCK_SERVICE_DESK_G1_4=1170;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_NACHDRUCK_SERVICE_DESK_G1_5=1171;
            
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_NACHDRUCK_SERVICE_DESK_G2_1=1172;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_NACHDRUCK_SERVICE_DESK_G2_2=1173;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_NACHDRUCK_SERVICE_DESK_G2_3=1174;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_NACHDRUCK_SERVICE_DESK_G2_4=1175;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_NACHDRUCK_SERVICE_DESK_G2_5=1176;
    
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_NACHDRUCK_SERVICE_DESK_G3_1=1177;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_NACHDRUCK_SERVICE_DESK_G3_2=1178;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_NACHDRUCK_SERVICE_DESK_G3_3=1179;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_NACHDRUCK_SERVICE_DESK_G3_4=1180;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_NACHDRUCK_SERVICE_DESK_G3_5=1181;
    
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_NACHDRUCK_SERVICE_DESK_G4_1=1182;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_NACHDRUCK_SERVICE_DESK_G4_2=1183;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_NACHDRUCK_SERVICE_DESK_G4_3=1184;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_NACHDRUCK_SERVICE_DESK_G4_4=1185;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_NACHDRUCK_SERVICE_DESK_G4_5=1186;
   
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_NACHDRUCK_SERVICE_DESK_G5_1=1187;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_NACHDRUCK_SERVICE_DESK_G5_2=1188;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_NACHDRUCK_SERVICE_DESK_G5_3=1189;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_NACHDRUCK_SERVICE_DESK_G5_4=1190;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_NACHDRUCK_SERVICE_DESK_G5_5=1191;
   
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_DRUCKER_BEI_ERSTZUGANG_G1_1=1192;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_DRUCKER_BEI_ERSTZUGANG_G1_2=1193;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_DRUCKER_BEI_ERSTZUGANG_G1_3=1194;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_DRUCKER_BEI_ERSTZUGANG_G1_4=1195;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_DRUCKER_BEI_ERSTZUGANG_G1_5=1196;
            
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_DRUCKER_BEI_ERSTZUGANG_G2_1=1197;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_DRUCKER_BEI_ERSTZUGANG_G2_2=1198;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_DRUCKER_BEI_ERSTZUGANG_G2_3=1199;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_DRUCKER_BEI_ERSTZUGANG_G2_4=1200;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_DRUCKER_BEI_ERSTZUGANG_G2_5=1201;
    
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_DRUCKER_BEI_ERSTZUGANG_G3_1=1202;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_DRUCKER_BEI_ERSTZUGANG_G3_2=1203;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_DRUCKER_BEI_ERSTZUGANG_G3_3=1204;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_DRUCKER_BEI_ERSTZUGANG_G3_4=1205;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_DRUCKER_BEI_ERSTZUGANG_G3_5=1206;
    
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_DRUCKER_BEI_ERSTZUGANG_G4_1=1207;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_DRUCKER_BEI_ERSTZUGANG_G4_2=1208;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_DRUCKER_BEI_ERSTZUGANG_G4_3=1209;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_DRUCKER_BEI_ERSTZUGANG_G4_4=1210;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_DRUCKER_BEI_ERSTZUGANG_G4_5=1211;
    
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_DRUCKER_BEI_ERSTZUGANG_G5_1=1212;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_DRUCKER_BEI_ERSTZUGANG_G5_2=1213;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_DRUCKER_BEI_ERSTZUGANG_G5_3=1214;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_DRUCKER_BEI_ERSTZUGANG_G5_4=1215;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_DRUCKER_BEI_ERSTZUGANG_G5_5=1216;
   
    /*XXX Noch nicht in neuer Oberfläche*/
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_SECOND_ZUORDNEN_GATTUNG_G1=1217;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_SECOND_ZUORDNEN_GATTUNG_G2=1218;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_SECOND_ZUORDNEN_GATTUNG_G3=1219;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_SECOND_ZUORDNEN_GATTUNG_G4=1220;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_SECOND_ZUORDNEN_GATTUNG_G5=1221;

    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_SECOND_ZUORDNEN_GATTUNG_TEXT_G1=1222;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_SECOND_ZUORDNEN_GATTUNG_TEXT_G2=1223;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_SECOND_ZUORDNEN_GATTUNG_TEXT_G3=1224;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_SECOND_ZUORDNEN_GATTUNG_TEXT_G4=1225;
    public static int AKKREDITIERUNG_P_PRAESENZ_STIMMKARTE_SECOND_ZUORDNEN_GATTUNG_TEXT_G5=1226;

    /*XXX Noch nicht in Oberfläche*/
    public static int AKKREDITIERUNG_P_PRAESENZ_BEI_ERSCHEINEN_ANDERE_VOLLMACHTEN_STORNIEREN=1227;
    
    /*XXX Noch nicht in Oberfläche*/
    public static int AKKREDITIERUNG_P_LFD_PRAESENZ_STORNIEREN_AUS_SAMMEL_MOEGLICH_0=1228;
    public static int AKKREDITIERUNG_P_LFD_PRAESENZ_STORNIEREN_AUS_SAMMEL_MOEGLICH_1_KIAV=1229;
    public static int AKKREDITIERUNG_P_LFD_PRAESENZ_STORNIEREN_AUS_SAMMEL_MOEGLICH_2_SRV=1230;
    public static int AKKREDITIERUNG_P_LFD_PRAESENZ_STORNIEREN_AUS_SAMMEL_MOEGLICH_3_ORGANISATORISCH=1231;
    public static int AKKREDITIERUNG_P_LFD_PRAESENZ_STORNIEREN_AUS_SAMMEL_MOEGLICH_4_BRIEFWAHL=1232;
    public static int AKKREDITIERUNG_P_LFD_PRAESENZ_STORNIEREN_AUS_SAMMEL_MOEGLICH_5_DAUERVOLLMACHT=1233;

    public static int AKKREDITIERUNG_P_LFD_PRAESENZ_DEAKTIVIEREN_AUS_SAMMEL_MOEGLICH_0=1234;
    public static int AKKREDITIERUNG_P_LFD_PRAESENZ_DEAKTIVIEREN_AUS_SAMMEL_MOEGLICH_1_KIAV=1235;
    public static int AKKREDITIERUNG_P_LFD_PRAESENZ_DEAKTIVIEREN_AUS_SAMMEL_MOEGLICH_2_SRV=1236;
    public static int AKKREDITIERUNG_P_LFD_PRAESENZ_DEAKTIVIEREN_AUS_SAMMEL_MOEGLICH_3_ORGANISATORISCH=1237;
    public static int AKKREDITIERUNG_P_LFD_PRAESENZ_DEAKTIVIEREN_AUS_SAMMEL_MOEGLICH_4_BRIEFWAHL=1238;
    public static int AKKREDITIERUNG_P_LFD_PRAESENZ_DEAKTIVIEREN_AUS_SAMMEL_MOEGLICH_5_DAUERVOLLMACHT=1239;

    public static int AKKREDITIERUNG_P_LFD_PRAESENZ_ERTEILEN_IN_SAMMEL_MOEGLICH_0=1240;
    public static int AKKREDITIERUNG_P_LFD_PRAESENZ_ERTEILEN_IN_SAMMEL_MOEGLICH_1_KIAV=1241;
    public static int AKKREDITIERUNG_P_LFD_PRAESENZ_ERTEILEN_IN_SAMMEL_MOEGLICH_2_SRV=1242;
    public static int AKKREDITIERUNG_P_LFD_PRAESENZ_ERTEILEN_IN_SAMMEL_MOEGLICH_3_ORGANISATORISCH=1243;
    public static int AKKREDITIERUNG_P_LFD_PRAESENZ_ERTEILEN_IN_SAMMEL_MOEGLICH_4_BRIEFWAHL=1244;
    public static int AKKREDITIERUNG_P_LFD_PRAESENZ_ERTEILEN_IN_SAMMEL_MOEGLICH_5_DAUERVOLLMACHT=1245;

    /*XXX Noch nicht in Oberfläche*/
    public static int AKKREDITIERUNG_P_LFD_HV_GESTARTET=1246;
    public static int AKKREDITIERUNG_P_LFD_HV_DELAYED=1247;
    
    public static int AKKREDITIERUNG_SK_OFFENLEGUNG_SRV=1248;
    public static int AKKREDITIERUNG_SK_OFFENLEGUNG_KIAV=1249;
    public static int AKKREDITIERUNG_SK_OFFENLEGUNG_DAUER=1250;
    public static int AKKREDITIERUNG_SK_OFFENLEGUNG_ORGA=1251;
    
    public static int AKKREDITIERUNG_FORMULAR_NACH_ERSTZUGANG=1252;
    public static int AKKREDITIERUNG_ZUSAETZLICHES_INITIALPASSWORT_BEI_ERSTZUGANG=1253;
    public static int AKKREDITIERUNG_SERVICE_DESK_SET_NR=1254;
    
    public static int AKKREDITIERUNG_LABELDRUCK_VERFAHREN=1255;
    public static int AKKREDITIERUNG_LABEL_FONT=1256;
    
    public static int AKKREDITIERUNG_LABEL_XPOS_1=1261;
    public static int AKKREDITIERUNG_LABEL_XPOS_2=1262;
    public static int AKKREDITIERUNG_LABEL_XPOS_3=1263;
    public static int AKKREDITIERUNG_LABEL_XPOS_4=1264;
    public static int AKKREDITIERUNG_LABEL_XPOS_5=1265;
    public static int AKKREDITIERUNG_LABEL_XPOS_6=1266;
    public static int AKKREDITIERUNG_LABEL_XPOS_7=1267;
    public static int AKKREDITIERUNG_LABEL_XPOS_8=1268;
    public static int AKKREDITIERUNG_LABEL_XPOS_9=1269;
    public static int AKKREDITIERUNG_LABEL_XPOS_10=1270;

    public static int AKKREDITIERUNG_LABEL_YPOS_1=1271;
    public static int AKKREDITIERUNG_LABEL_YPOS_2=1272;
    public static int AKKREDITIERUNG_LABEL_YPOS_3=1273;
    public static int AKKREDITIERUNG_LABEL_YPOS_4=1274;
    public static int AKKREDITIERUNG_LABEL_YPOS_5=1275;
    public static int AKKREDITIERUNG_LABEL_YPOS_6=1276;
    public static int AKKREDITIERUNG_LABEL_YPOS_7=1277;
    public static int AKKREDITIERUNG_LABEL_YPOS_8=1278;
    public static int AKKREDITIERUNG_LABEL_YPOS_9=1279;
    public static int AKKREDITIERUNG_LABEL_YPOS_10=1280;

    public static int AKKREDITIERUNG_LABEL_FONTSIZE_1=1281;
    public static int AKKREDITIERUNG_LABEL_FONTSIZE_2=1282;
    public static int AKKREDITIERUNG_LABEL_FONTSIZE_3=1283;
    public static int AKKREDITIERUNG_LABEL_FONTSIZE_4=1284;
    public static int AKKREDITIERUNG_LABEL_FONTSIZE_5=1285;
    public static int AKKREDITIERUNG_LABEL_FONTSIZE_6=1286;
    public static int AKKREDITIERUNG_LABEL_FONTSIZE_7=1287;
    public static int AKKREDITIERUNG_LABEL_FONTSIZE_8=1288;
    public static int AKKREDITIERUNG_LABEL_FONTSIZE_9=1289;
    public static int AKKREDITIERUNG_LABEL_FONTSIZE_10=1290;

    public static int AKKREDITIERUNG_LABEL_ZEILEN_BEDINGUNG_1=1291;
    public static int AKKREDITIERUNG_LABEL_ZEILEN_BEDINGUNG_2=1292;
    public static int AKKREDITIERUNG_LABEL_ZEILEN_BEDINGUNG_3=1293;
    public static int AKKREDITIERUNG_LABEL_ZEILEN_BEDINGUNG_4=1294;
    public static int AKKREDITIERUNG_LABEL_ZEILEN_BEDINGUNG_5=1295;
    public static int AKKREDITIERUNG_LABEL_ZEILEN_BEDINGUNG_6=1296;
    public static int AKKREDITIERUNG_LABEL_ZEILEN_BEDINGUNG_7=1297;
    public static int AKKREDITIERUNG_LABEL_ZEILEN_BEDINGUNG_8=1298;
    public static int AKKREDITIERUNG_LABEL_ZEILEN_BEDINGUNG_9=1299;
    public static int AKKREDITIERUNG_LABEL_ZEILEN_BEDINGUNG_10=1300;

    public static int AKKREDITIERUNG_LABEL_LABEL_STRING_1=1301;
    public static int AKKREDITIERUNG_LABEL_LABEL_STRING_2=1302;
    public static int AKKREDITIERUNG_LABEL_LABEL_STRING_3=1303;
    public static int AKKREDITIERUNG_LABEL_LABEL_STRING_4=1304;
    public static int AKKREDITIERUNG_LABEL_LABEL_STRING_5=1305;
    public static int AKKREDITIERUNG_LABEL_LABEL_STRING_6=1306;
    public static int AKKREDITIERUNG_LABEL_LABEL_STRING_7=1307;
    public static int AKKREDITIERUNG_LABEL_LABEL_STRING_8=1308;
    public static int AKKREDITIERUNG_LABEL_LABEL_STRING_9=1309;
    public static int AKKREDITIERUNG_LABEL_LABEL_STRING_10=1310;
   
    public static int AKKREDITIERUNG_LABEL_QRCODE=1311;
    

    /**Abstimmungs-Parameter*/
    public static int ABSTIMMUNG_WEISUNG_NICHT_MARKIERTE_SPEICHERN_ALS_SRV=2001;
    public static int ABSTIMMUNG_WEISUNG_NICHT_MARKIERTE_SPEICHERN_ALS_BRIEFWAHL=2002;
    public static int ABSTIMMUNG_WEISUNG_NICHT_MARKIERTE_SPEICHERN_ALS_KIAV=2003;
    public static int ABSTIMMUNG_WEISUNG_NICHT_MARKIERTE_SPEICHERN_ALS_DAUER=2004;
    public static int ABSTIMMUNG_WEISUNG_NICHT_MARKIERTE_SPEICHERN_ALS_ORG=2005;

    public static int ABSTIMMUNG_WEISUNG_HV_NICHT_MARKIERTE_SPEICHERN_ALS=2006;
    public static int ABSTIMMUNG_ABSTIMMUNG_NICHT_MARKIERTE_SPEICHERN_ALS=2007;

    public static int ABSTIMMUNG_WEISUNG_VORBELEGUNG_MIT_SRV=2008;
    public static int ABSTIMMUNG_WEISUNG_VORBELEGUNG_MIT_BRIEFWAHL=2009;
    public static int ABSTIMMUNG_WEISUNG_VORBELEGUNG_MIT_KIAV=2010;
    public static int ABSTIMMUNG_WEISUNG_VORBELEGUNG_MIT_DAUER=2011;
    public static int ABSTIMMUNG_WEISUNG_VORBELEGUNG_MIT_ORG=2012;

    
    public static int ABSTIMMUNG_WEISUNG_HV_VORBELEGEN_MIT=2013;
    public static int ABSTIMMUNG_ABSTIMMUNG_VORBELEGEN_MIT=2014;
    
    public static int ABSTIMMUNG_EINGABEZWANG_SRV=2015;
    public static int ABSTIMMUNG_EINGABEZWANG_BRIEFWAHL=2016;
    public static int ABSTIMMUNG_EINGABEZWANG_KIAV=2017;
    public static int ABSTIMMUNG_EINGABEZWANG_DAUER=2018;
    public static int ABSTIMMUNG_EINGABEZWANG_ORG=2019;

    public static int ABSTIMMUNG_EINGABEZWANG_WEISUNG_HV=2020;
    public static int ABSTIMMUNG_EINGABEZWANG_ABSTIMMUNG=2021;

    public static int ABSTIMMUNG_UNDEFINIERTE_WEISUNGEN_ZAEHLEN_ALS=2022;
    public static int ABSTIMMUNG_UNGUELTIGE_ZAEHLEN_ALS_ENTHALTUNG=2023;
    public static int ABSTIMMUNG_NICHT_TEILNAHME_MOEGLICH=2024;
    public static int ABSTIMMUNG_VEROEFFENTLICHT_IM_BUNDESANZEIGER_VOM=2025;
    public static int ABSTIMMUNG_SORTIERUNG_DRUCKAUSGABE_INDIVIDUELL=2026;

    public static int ABSTIMMUNG_TEXT_VERWENDEN_TABLET=2027;
    public static int ABSTIMMUNG_TEXT_VERWENDEN_FORMULAR=2028;
    public static int ABSTIMMUNG_ABSTIMMEN_DUERFEN_NUR_PRAESENTE_ODER_PRAESENTE_UND_PRAESENT_GEWESENE=2029;
    public static int ABSTIMMUNG_ABSTIMMEN_TABLET_NICHT_PRAESENTE_WERDEN_PRAESENT_GESETZT=2030;
    public static int ABSTIMMUNG_PRIORISIERUNG_ELEKTRONISCH_VOR_PAPIER_ODER_PAPIER_VOR_ELEKTRONISCH=2031;
    public static int ABSTIMMUNG_BEI_MEHRFACHER_STIMMABGABE_LETZTE_ABGABE_GILT_ODER_UNGLEICHE_UNGUELTIG=2032;
    public static int ABSTIMMUNG_BEI_ABSTIMMUNG_EINTRITTSKARTENNUMMER_ZULAESSIG=2033;
    public static int ABSTIMMUNG_BEI_TABLET_ABSTIMMUNG_NUR_AUFGERUFENE_STIMMZETTELNUMMER=2034;
    public static int ABSTIMMUNG_BEI_TABLET_ABSTIMMUNG_BLAETTERN=2035;
    
    public static int ABSTIMMUNG_ANZAHL_JA_JE_ABSTIMMUNGSGRUPPE_1=2036;
    public static int ABSTIMMUNG_ANZAHL_JA_JE_ABSTIMMUNGSGRUPPE_2=2037;
    public static int ABSTIMMUNG_ANZAHL_JA_JE_ABSTIMMUNGSGRUPPE_3=2038;
    public static int ABSTIMMUNG_ANZAHL_JA_JE_ABSTIMMUNGSGRUPPE_4=2039;
    public static int ABSTIMMUNG_ANZAHL_JA_JE_ABSTIMMUNGSGRUPPE_5=2040;
    public static int ABSTIMMUNG_ANZAHL_JA_JE_ABSTIMMUNGSGRUPPE_6=2041;
    public static int ABSTIMMUNG_ANZAHL_JA_JE_ABSTIMMUNGSGRUPPE_7=2042;
    public static int ABSTIMMUNG_ANZAHL_JA_JE_ABSTIMMUNGSGRUPPE_8=2043;
    public static int ABSTIMMUNG_ANZAHL_JA_JE_ABSTIMMUNGSGRUPPE_9=2044;
    public static int ABSTIMMUNG_ANZAHL_JA_JE_ABSTIMMUNGSGRUPPE_10=2045;
    
    public static int ABSTIMMUNG_BEI_TABLET_ALLES_JA=2046;
    public static int ABSTIMMUNG_BEI_TABLET_ALLES_NEIN=2047;
    public static int ABSTIMMUNG_BEI_TABLE_ALLES_ENTHALTUNG=2048;
    
    public static int ABSTIMMUNG_BEI_TABLET_GESAMTMARKIERUNG_TEXT_ANZEIGEN=2049;
    public static int ABSTIMMUNG_BEI_TABLET_GESAMTMARKIERUNG_FUER_ALLE=2050;
    public static int ABSTIMMUNG_BEI_TABLET_TEXT_KURZ_ODER_LANG=2051;
    
    public static int ABSTIMMUNG_ABSTIMMUNGS_LOAD_BEI_AKTIVIERUNG_IM_ABSTIMMUNGSABLAUF=2052;
    
    public static int ABSTIMMUNG_BEI_TABLET_FARBE_JA=2053;
    public static int ABSTIMMUNG_BEI_TABLET_FARBE_NEIN=2054;
    public static int ABSTIMMUNG_BEI_TABLET_FARBE_ENTHALTUNG=2055;
     
    public static int ABSTIMMUNG_BEI_TABLET_FARBE_UNMARKIERT_JA=2056;
    public static int ABSTIMMUNG_BEI_TABLET_FARBE_UNMARKIERT_NEIN=2057;
    public static int ABSTIMMUNG_BEI_TABLET_FARBE_UNMARKIERT_ENTHALTUNG=2058;
     
    public static int ABSTIMMUNG_BEI_TABLET_FARBE_GESAMTMARKIERUNG_JA=2059;
    public static int ABSTIMMUNG_BEI_TABLET_FARBE_GESAMTMARKIERUNG_NEIN=2060;
    public static int ABSTIMMUNG_BEI_TABLET_FARBE_GESAMTMARKIERUNG_ENTHALTUNG=2061;
     
    public static int ABSTIMMUNG_IN_100_PZ_AUCH_ENTHALTUNGEN=2062;
    public static int ABSTIMMUNG_IN_100_PZ_AUCH_UNGUELTIGE=2063;
    public static int ABSTIMMUNG_IN_100_PZ_AUCH_NICHT_STIMMBERECHTIGTE=2064;
    public static int ABSTIMMUNG_IN_100_PZ_AUCH_NICHT_TEILNAHME=2065;
    
    public static int ABSTIMMUNG_AUSWERTEN_PP_LISTE_ZEILEN=2066;
    public static int ABSTIMMUNG_IMPLIZITE_STIMMABABEN_AUTOMATISCH_VERWALTEN=2067;
    /*XXX*/
    public static int ABSTIMMUNG_ANZEIGE_BEZEICHNUNG_KURZ_AKTIV=2068;
    
    public static int ABSTIMMUNG_WEISUNGEN_GEGENANTRAEGE_PORTAL_SEPARAT=2069;
    public static int ABSTIMMUNG_WEISUNGEN_GEGENANTRAEGE_INTERN_SEPARAT=2070;
    public static int ABSTIMMUNG_WEISUNGEN_GEGENANTRAEGE_VERLASSEN_HV_SEPARAT=2071;
    
    public static int ABSTIMMUNG_STIMMZETTELDRUCK_ABSTIMMUNGSBLOCK_BASIS=2072;
    public static int ABSTIMMUNG_STIMMZETTELDRUCK_ANZAHL_STIMMZETTEL=2073;
    public static int ABSTIMMUNG_BRIEFWAHL_AUSGEBEN_IN_ABSTIMMUNGSERGEBNIS=2074;
    /*Noch nicht machbar:
     * impliziteStimmabgabenAutomatischVerwalten
     * 
     */
    
    public static int PORTAL_testModus=3001;
    
    public static int PORTAL_dauerhaftesPasswortMoeglich=3002;
    public static int PORTAL_registrierungFuerEmailVersandMoeglich=3003;
    public static int PORTAL_emailVersandRegistrierungOderWiderspruch=3004;
    public static int PORTAL_adressaenderungMoeglich=3005;
    public static int PORTAL_kommunikationsspracheAuswahl=3006;
    public static int PORTAL_publikationenAnbieten=3007;
    public static int PORTAL_kontaktDetailsAnbieten=3008;
    public static int PORTAL_emailNurBeiEVersandOderPasswort=3009;
    
    public static int PORTAL_cookieHinweis=3010;
    public static int PORTAL_inHVPortalKeineEinstellungenFuerAktionaere=3011;
    public static int PORTAL_inHVPortalKeineEmailUndKeinPasswortFuerAktionaere=3012;
    public static int PORTAL_mailEingabeServiceline=3013;
    
    public static int PORTAL_emailVersandZweitEMailAusRegister=3014;
    
    
    public static int PORTAL_srvAngeboten=3030;
    public static int PORTAL_briefwahlAngeboten=3031;
    public static int PORTAL_vollmachtDritteAngeboten=3032;
    public static int PORTAL_vollmachtKIAVAngeboten=3033;
    public static int PORTAL_weisungenAktuellNichtMoeglich=3034;
    public static int PORTAL_weisungenAktuellNichtMoeglichAberBriefwahlSchon=3035;
    public static int PORTAL_portalFuerGattungMoeglich_1=3036;
    public static int PORTAL_portalFuerGattungMoeglich_2=3037;
    public static int PORTAL_portalFuerGattungMoeglich_3=3038;
    public static int PORTAL_portalFuerGattungMoeglich_4=3039;
    public static int PORTAL_portalFuerGattungMoeglich_5=3040;
    public static int PORTAL_stimmabgabeFuerGattungMoeglich_1=3041;
    public static int PORTAL_stimmabgabeFuerGattungMoeglich_2=3042;
    public static int PORTAL_stimmabgabeFuerGattungMoeglich_3=3043;
    public static int PORTAL_stimmabgabeFuerGattungMoeglich_4=3044;
    public static int PORTAL_stimmabgabeFuerGattungMoeglich_5=3045;
    public static int PORTAL_gastkartenAnforderungMoeglich=3046;
    public static int PORTAL_oeffentlicheIDMoeglich=3047;
    public static int PORTAL_zusaetzlicheEKDritteMoeglich=3048;
    public static int PORTAL_ekUndWeisungGleichzeitigMoeglich=3049;
    public static int PORTAL_briefwahlZusaetzlichZuSRVMoeglich=3050;
    public static int PORTAL_srvZusaetzlichZuBriefwahlMoeglich=3051;
    public static int PORTAL_vollmachtDritteUndAndereWKMoeglich=3052;
    public static int PORTAL_briefwahlAlsOnlineStimmabgabe=3053;
    
    public static int PORTAL_multiUserImPortalIgnorieren=3060;
    public static int PORTAL_handhabungWeisungDurchVerschiedene=3061;
    public static int PORTAL_sammelkartenFuerAenderungSperren=3062;
    
    public static int PORTAL_erklAnPos1=3070;
    public static int PORTAL_erklAnPos2=3071;
    public static int PORTAL_erklAnPos3=3072;
    public static int PORTAL_erklAnPos4=3073;
    public static int PORTAL_erklAnPos5=3074;
   
    public static int PORTAL_ekSelbstMoeglich=3080;
    public static int PORTAL_ekVollmachtMoeglich=3081;
    public static int PORTAL_ek2PersonengemeinschaftMoeglich=3082;
    public static int PORTAL_ek2MitOderOhneVollmachtMoeglich=3083;
    public static int PORTAL_ek2SelbstMoeglich=3084;
    
    public static int PORTAL_ekVersandFuerAlleImPortalAngeforderten=3085;
    public static int PORTAL_anmeldenOhneWeitereWK=3086;
    
    public static int PORTAL_bestaetigungBeiWeisung=3087;
    public static int PORTAL_bestaetigungBeiWeisungMitTOP=3088;
    public static int PORTAL_vollmachtsnachweisAufStartseiteAktiv=3089;
    public static int PORTAL_bestaetigungStimmabgabeNachHV=3090;

    public static int PORTAL_lfdHVDialogVeranstaltungenInMenue=3100;
    public static int PORTAL_lfdHVBeiratswahlInMenue=3101;
    public static int PORTAL_lfdHVGeneralversammlungInMenue=3102;
    public static int PORTAL_lfdHVGeneralversammlungBriefwahlInMenue=3103;
    public static int PORTAL_lfdHVUnterlagenInMenue=3104;
    public static int PORTAL_lfdHVEinstellungenInMenue=3105;
    public static int PORTAL_lfdHVGeneralversammlungTeilnahmeInMenue=3106;
    public static int PORTAL_lfdHVGeneralversammlungTeilnahmeGast=3107;
    
    public static int PORTAL_dialogveranstaltungAktiv=3120;
    
    public static int PORTAL_datumsformatDE=3121;
    public static int PORTAL_datumsformatEN=3122;

    public static int PORTAL_letzterAktienregisterUpdate=3123;
    
    public static int PORTAL_bestaetigenDialog=3130;
    public static int PORTAL_quittungDialog=3131;
    public static int PORTAL_artSprachumschaltung=3132;
    public static int PORTAL_varianteDialogablauf=3133;
    public static int PORTAL_ku178SepaIstAktiv=3134;
    
    public static int PORTAL_passwortCaseSensitiv=3135;
    public static int PORTAL_passwortMindestLaenge=3136;
    public static int PORTAL_verfahrenPasswortVergessen=3137;
    public static int PORTAL_verfahrenPasswortVergessenAblauf=3138;
    public static int PORTAL_verfahrenPasswortVergessenBeiEmailHinterlegtAuchPost=3139;
    public static int PORTAL_loginGesperrt=3140;
    public static int PORTAL_loginGesperrtTextDeutsch=3141;
    public static int PORTAL_loginGesperrtTextEnglisch=3142;
    public static int PORTAL_loginIPTrackingAktiv=3143;
    public static int PORTAL_linkEmailEnthaeltLinkOderCode=3144;
    public static int PORTAL_emailBestaetigenIstZwingend=3145;
    public static int PORTAL_absendeMailAdresse=3146;
    public static int PORTAL_passwortPerPostPruefen=3147;
    public static int PORTAL_loginVerfahren=3148;
    public static int PORTAL_captchaVerwenden=3149;
    public static int PORTAL_loginVerzoegerungAbVersuch=3150;
    public static int PORTAL_loginVerzoegerungSekunden=3151;
    public static int PORTAL_alternativeLoginKennung=3152;
    public static int PORTAL_teilnehmerKannSichWeitereKennungenZuordnen=3153;
    public static int PORTAL_bestaetigungPerEmailUeberallZulassen=3154;
    public static int PORTAL_kennungAufbereiten=3155;
    public static int PORTAL_kennungAufbereitenFuerAnzeige=3156;
    public static int PORTAL_logoutZiel=3157;

    public static int PORTAL_bestaetigungSeparateAktionaersPortalHinweiseErforderlich=3170;
    public static int PORTAL_bestaetigenHinweisAktionaersportal=3171;
    public static int PORTAL_bestaetigungSeparateHVPortalHinweiseErforderlich=3172;
    public static int PORTAL_bestaetigenHinweisHVportal=3173;
    public static int PORTAL_separateDatenschutzerklaerung=3174;
    public static int PORTAL_bestaetigenHinweisWeitere=3175;
    public static int PORTAL_separateNutzungshinweise=3176;
    public static int PORTAL_erstregistrierungImmer=3177;
    public static int PORTAL_separateTeilnahmebedingungenFuerGewinnspiel=3178;
    public static int PORTAL_kontaktFenster=3179;
    public static int PORTAL_impressumEmittent=3180;
    public static int PORTAL_bestaetigungsseiteEinstellungen=3181;
    public static int PORTAL_reihenfolgeRegistrierung=3182;

    public static int PORTAL_pNichtmarkiertSpeichernAls=3190;
    
    public static int PORTAL_gesamtMarkierungJa=3191;
    public static int PORTAL_gesamtMarkierungNein=3192;
    public static int PORTAL_gesamtMarkierungEnthaltung=3193;
    public static int PORTAL_gesamtMarkierungImSinne=3194;
    public static int PORTAL_gesamtMarkierungGegenSinne=3195;

    public static int PORTAL_gesamtMarkierungAllesLoeschen=3196;

    public static int PORTAL_markierungJa=3197;
    public static int PORTAL_markierungNein=3198;
    public static int PORTAL_markierungEnthaltung=3199;
    public static int PORTAL_markierungLoeschen=3200;

    public static int PORTAL_gegenantraegeWeisungenMoeglich=3201;

    public static int PORTAL_gegenantragsText=3202;

    public static int PORTAL_checkboxBeiSRV=3203;
    public static int PORTAL_checkboxBeiKIAV=3204;
    public static int PORTAL_checkboxBeiBriefwahl=3205;

    public static int PORTAL_checkboxBeiVollmacht=3206;

    public static int PORTAL_jnAbfrageBeiWeisungQuittung=3207;

    public static int PORTAL_personenAnzeigeAnredeMitAufnahmen=3210;
    public static int PORTAL_textPostfachMitAufnahmen=3211;
    public static int PORTAL_anzeigeStimmenKennung=3212;
    
    public static int PORTAL_timeoutAufLang=3213;
    public static int PORTAL_websocketsMoeglich=3214;
    public static int PORTAL_doppelLoginGesperrt=3215;
    
    public static int PORTAL_nurRawLiveAbstimmung=3216;
    public static int PORTAL_onlineTeilnehmerAbfragen=3216;
    public static int PORTAL_onlineTeilnahmeSeparateNutzungsbedingungen=3216;
    public static int PORTAL_onlineTeilnahmeTeilnehmerNameBestaetigen=3216;
    public static int PORTAL_onlineTeilnahmeAktionaerAlsGast=3216;
    public static int PORTAL_onlineTeilnahmeGastInSeparatemMenue=3216;
    public static int PORTAL_onlineTeilnahmeNurFuerFreiwilligAngemeldete=3217;
    public static int PORTAL_onlineAbstimmungBerechtigungSeparatPruefen=3218;
    public static int PORTAL_hybridTeilnahmeAktiv=3219;
    
    public static int PORTAL_veranstaltungMailVerschicken=3220;
    public static int PORTAL_veranstaltungPersonenzahlEingeben=3221;
    public static int PORTAL_veranstaltungMehrfachAuswaehlbarJeGruppe=3222;
    
    public static int PORTAL_veranstaltungenAktivFuerGattung_1=3224;
    public static int PORTAL_veranstaltungenAktivFuerGattung_2=3225;
    public static int PORTAL_veranstaltungenAktivFuerGattung_3=3226;
    public static int PORTAL_veranstaltungenAktivFuerGattung_4=3227;
    public static int PORTAL_veranstaltungenAktivFuerGattung_5=3228;
    
    public static int PORTAL_freiwillingAnmeldenPraesenzOderOnline=3230;
    public static int PORTAL_freiwilligeAnmeldungEKDruckMoeglich=3231;
    public static int PORTAL_freiwilligeAnmeldungNurPapier=3232;
    public static int PORTAL_freiwilligeAnmeldungMitVertretereingabe=3233;
    public static int PORTAL_freiwilligeAnmeldungZweiPersonenFuerMinderjaehrigeMoeglich=3234;
    
    public static int PORTAL_freiwilligeAnmeldungAktivFuerGattung_1=3235;
    public static int PORTAL_freiwilligeAnmeldungAktivFuerGattung_2=3236;
    public static int PORTAL_freiwilligeAnmeldungAktivFuerGattung_3=3237;
    public static int PORTAL_freiwilligeAnmeldungAktivFuerGattung_4=3238;
    public static int PORTAL_freiwilligeAnmeldungAktivFuerGattung_5=3239;

    public static int PORTAL_streamNurFuerAngemeldete=3250;
    public static int PORTAL_streamAnbieter=3251;
    public static int PORTAL_streamLink=3252;
    public static int PORTAL_streamID=3253;
    public static int PORTAL_streamTestlinkWirdAngeboten=3254;
    public static int PORTAL_streamAnbieter2=3255;
    public static int PORTAL_streamLink2=3256;
    public static int PORTAL_streamID2=3257;

    public static int PORTAL_shrinkFormat=3260;
    public static int PORTAL_shrinkAufloesung=3261;
    public static int PORTAL_videoBotschaftProjectId=3262;
    public static int PORTAL_videoBotschaftApiKey=3263;
    
    public static int PORTAL_konfSessionId=3271;
    public static int PORTAL_konfEventId=3272;
    
    public static int PORTAL_konfRaumAnzahl_0=3273;
    public static int PORTAL_konfRaumAnzahl_1=3274;

    public static int PORTAL_konfRaumId_0_0=3280;
    public static int PORTAL_konfRaumId_0_1=3281;
    public static int PORTAL_konfRaumId_0_2=3282;
    public static int PORTAL_konfRaumId_0_3=3283;
    public static int PORTAL_konfRaumId_0_4=3284;
    public static int PORTAL_konfRaumId_0_5=3285;

    public static int PORTAL_konfRaumId_1_0=3286;
    public static int PORTAL_konfRaumId_1_1=3287;
    public static int PORTAL_konfRaumId_1_2=3288;
    public static int PORTAL_konfRaumId_1_3=3289;
    public static int PORTAL_konfRaumId_1_4=3290;
    public static int PORTAL_konfRaumId_1_5=3291;

    public static int PORTAL_konfBackupServer=3292;

    public static int PORTAL_konfRaumBId_0_0=3300;
    public static int PORTAL_konfRaumBId_0_1=3301;
    public static int PORTAL_konfRaumBId_0_2=3302;
    public static int PORTAL_konfRaumBId_0_3=3303;
    public static int PORTAL_konfRaumBId_0_4=3304;
    public static int PORTAL_konfRaumBId_0_5=3305;

    public static int PORTAL_konfRaumBId_1_0=3306;
    public static int PORTAL_konfRaumBId_1_1=3307;
    public static int PORTAL_konfRaumBId_1_2=3308;
    public static int PORTAL_konfRaumBId_1_3=3309;
    public static int PORTAL_konfRaumBId_1_4=3310;
    public static int PORTAL_konfRaumBId_1_5=3311;

    public static int PORTAL_konfRaumBIdPW_0_0=3312;
    public static int PORTAL_konfRaumBIdPW_0_1=3313;
    public static int PORTAL_konfRaumBIdPW_0_2=3314;
    public static int PORTAL_konfRaumBIdPW_0_3=3315;
    public static int PORTAL_konfRaumBIdPW_0_4=3316;
    public static int PORTAL_konfRaumBIdPW_0_5=3317;

    public static int PORTAL_konfRaumBIdPW_1_0=3318;
    public static int PORTAL_konfRaumBIdPW_1_1=3319;
    public static int PORTAL_konfRaumBIdPW_1_2=3320;
    public static int PORTAL_konfRaumBIdPW_1_3=3321;
    public static int PORTAL_konfRaumBIdPW_1_4=3322;
    public static int PORTAL_konfRaumBIdPW_1_5=3323;

    public static int PORTAL_konfBackupAktiv=3324;
    public static int PORTAL_konfGlobaleTestraeumeNutzen=3325;

    public static int PORTAL_fragenStellerAbfragen=3330;
    public static int PORTAL_fragenNameAbfragen=3331;
    public static int PORTAL_fragenKontaktdatenAbfragen=3332;
    public static int PORTAL_fragenKontaktdatenEMailVorschlagen=3333;
    public static int PORTAL_fragenKontaktdatenTelefonAbfragen=3334;
    public static int PORTAL_fragenKurztextAbfragen=3335;
    public static int PORTAL_fragenTopListeAnbieten=3336;
    public static int PORTAL_fragenLangtextAbfragen=3337;
    public static int PORTAL_fragenZurueckziehenMoeglich=3338;
    public static int PORTAL_fragenLaenge=3339;
    public static int PORTAL_fragenAnzahlJeAktionaer=3340;
    public static int PORTAL_fragenStellerZulaessig=3341;
    public static int PORTAL_fragenRueckfragenErmoeglichen=3342;
    public static int PORTAL_fragenMailBeiEingang=3343;
    public static int PORTAL_fragenMailVerteiler1=3344;
    public static int PORTAL_fragenMailVerteiler2=3345;
    public static int PORTAL_fragenMailVerteiler3=3346;
    public static int PORTAL_fragenHinweisVorbelegenMit=3347;
    public static int PORTAL_fragenHinweisGelesen=3348;
    public static int PORTAL_fragenZurueckziehenMoeglichNurWennAktiv=3349;
    public static int PORTAL_fragenExternerZugriff=3350;
    public static int PORTAL_fragenTextInOberflaecheLang=3351;
    public static int PORTAL_fragenTextInOberflaecheKurz=3352;

    public static int PORTAL_fragenAngeboten=3365;
    public static int PORTAL_fragenNurFuerAngemeldete=3366;
    public static int PORTAL_fragenBisAktien=3367;
    public static int PORTAL_fragenAbAktien=3368;
    public static int PORTAL_fragenAnzahlStufe2=3369;
    public static int PORTAL_fragenLaengeStufe2=3370;
    public static int PORTAL_fragenAnzahlStufe3=3371;
    public static int PORTAL_fragenLaengeStufe3=3372;
    public static int PORTAL_fragenAnzahlStufe4=3373;
    public static int PORTAL_fragenLaengeStufe4=3374;

    public static int PORTAL_wortmeldungArt=3400;
    public static int PORTAL_wortmeldungStellerAbfragen=3401;
    public static int PORTAL_wortmeldungNameAbfragen=3402;
    public static int PORTAL_wortmeldungKontaktdatenAbfragen=3403;
    public static int PORTAL_wortmeldungKontaktdatenEMailVorschlagen=3404;
    public static int PORTAL_wortmeldungKontaktdatenTelefonAbfragen=3405;
    public static int PORTAL_wortmeldungKurztextAbfragen=3406;
    public static int PORTAL_wortmeldungTopListeAnbieten=3407;
    public static int PORTAL_wortmeldungLangtextAbfragen=3408;
    public static int PORTAL_wortmeldungZurueckziehenMoeglich=3409;
    public static int PORTAL_wortmeldungLaenge=3410;
    public static int PORTAL_wortmeldungAnzahlJeAktionaer=3411;
    public static int PORTAL_wortmeldungStellerZulaessig=3412;
    public static int PORTAL_wortmeldungListeAnzeigen=3413;
    public static int PORTAL_wortmeldungVLListeAnzeigen=3414;
    public static int PORTAL_wortmeldungMailBeiEingang=3415;
    public static int PORTAL_wortmeldungMailVerteiler1=3416;
    public static int PORTAL_wortmeldungMailVerteiler2=3417;
    public static int PORTAL_wortmeldungMailVerteiler3=3418;
    public static int PORTAL_wortmeldungHinweisVorbelegenMit=3419;
    public static int PORTAL_wortmeldungHinweisGelesen=3420;
    public static int PORTAL_wortmeldungZurueckziehenMoeglichNurWennAktiv=3421;
    public static int PORTAL_wortmeldungInhaltsHinweiseAktiv=3422;
    public static int PORTAL_wortmeldungTestDurchfuehren=3423;
    public static int PORTAL_wortmeldungRedeAufrufZweitenVersuchDurchfuehren=3424;
    public static int PORTAL_wortmeldungNachTestManuellInRednerlisteAufnehmen=3425;
    public static int PORTAL_wortmeldungNurEineOffeneZulaessig=3426;
    public static int PORTAL_wortmeldungTextInOberflaecheLang=3427;
    public static int PORTAL_wortmeldungTextInOberflaecheKurz=3428;
    
    public static int PORTAL_wortmeldetischSetNr=3440;
    public static int PORTALschriftgroesseVersammlunsleiterView_=3441;

    public static int PORTAL_widerspruecheStellerAbfragen=3450;
    public static int PORTAL_widerspruecheNameAbfragen=3451;
    public static int PORTAL_widerspruecheKontaktdatenAbfragen=3452;
    public static int PORTAL_widerspruecheKontaktdatenEMailVorschlagen=3453;
    public static int PORTAL_widerspruecheKontaktdatenTelefonAbfragen=3454;
    public static int PORTAL_widerspruecheKurztextAbfragen=3455;
    public static int PORTAL_widerspruecheTopListeAnbieten=3456;
    public static int PORTAL_widerspruecheLangtextAbfragen=3457;
    public static int PORTAL_widerspruecheZurueckziehenMoeglich=3458;
    public static int PORTAL_widerspruecheLaenge=3459;
    public static int PORTAL_widerspruecheAnzahlJeAktionaer=3460;
    public static int PORTAL_widerspruecheStellerZulaessig=3461;
    public static int PORTAL_widerspruecheMailBeiEingang=3462;
    public static int PORTAL_widerspruecheMailVerteiler1=3463;
    public static int PORTAL_widerspruecheMailVerteiler2=3464;
    public static int PORTAL_widerspruecheMailVerteiler3=3465;
    public static int PORTAL_widerspruecheHinweisVorbelegenMit=3466;
    public static int PORTAL_widerspruecheHinweisGelesen=3467;
    public static int PORTAL_widerspruecheZurueckziehenMoeglichNurWennAktiv=3468;
    public static int PORTAL_widerspruecheTextInOberflaecheLang=3469;
    public static int PORTAL_widerspruecheTextInOberflaecheKurz=3470;
    
    public static int PORTAL_antraegeStellerAbfragen=3490;
    public static int PORTAL_antraegeNameAbfragen=3491;
    public static int PORTAL_antraegeKontaktdatenAbfragen=3492;
    public static int PORTAL_antraegeKontaktdatenEMailVorschlagen=3493;
    public static int PORTAL_antraegeKontaktdatenTelefonAbfragen=3494;
    public static int PORTAL_antraegeKurztextAbfragen=3495;
    public static int PORTAL_antraegeTopListeAnbieten=3496;
    public static int PORTAL_antraegeLangtextAbfragen=3497;
    public static int PORTAL_antraegeZurueckziehenMoeglich=3498;
    public static int PORTAL_antraegeLaenge=3499;
    public static int PORTAL_antraegeAnzahlJeAktionaer=3500;
    public static int PORTAL_antraegeStellerZulaessig=3501;
    public static int PORTAL_antraegeMailBeiEingang=3502;
    public static int PORTAL_antraegeMailVerteiler1=3503;
    public static int PORTAL_antraegeMailVerteiler2=3504;
    public static int PORTAL_antraegeMailVerteiler3=3505;
    public static int PORTAL_antraegeHinweisVorbelegenMit=3506;
    public static int PORTAL_antraegeHinweisGelesen=3507;
    public static int PORTAL_antraegeZurueckziehenMoeglichNurWennAktiv=3508;
    public static int PORTAL_antraegeTextInOberflaecheLang=3509;
    public static int PORTAL_antraegeTextInOberflaecheKurz=3510;

    public static int PORTAL_sonstMitteilungenStellerAbfragen=3520;
    public static int PORTAL_sonstMitteilungenNameAbfragen=3521;
    public static int PORTAL_sonstMitteilungenKontaktdatenAbfragen=3522;
    public static int PORTAL_sonstMitteilungenKontaktdatenEMailVorschlagen=3523;
    public static int PORTAL_sonstMitteilungenKontaktdatenTelefonAbfragen=3524;
    public static int PORTAL_sonstMitteilungenKurztextAbfragen=3525;
    public static int PORTAL_sonstMitteilungenTopListeAnbieten=3526;
    public static int PORTAL_sonstMitteilungenLangtextAbfragen=3527;
    public static int PORTAL_sonstMitteilungenZurueckziehenMoeglich=3528;
    public static int PORTAL_sonstMitteilungenLaenge=3529;
    public static int PORTAL_sonstMitteilungenAnzahlJeAktionaer=3530;
    public static int PORTAL_sonstMitteilungenStellerZulaessig=3531;
    public static int PORTAL_sonstMitteilungenMailBeiEingang=3532;
    public static int PORTAL_sonstMitteilungenMailVerteiler1=3533;
    public static int PORTAL_sonstMitteilungenMailVerteiler2=3534;
    public static int PORTAL_sonstMitteilungenMailVerteiler3=3535;
    public static int PORTAL_sonstMitteilungenHinweisVorbelegenMit=3536;
    public static int PORTAL_sonstMitteilungenHinweisGelesen=3537;
    public static int PORTAL_sonstMitteilungenZurueckziehenMoeglichNurWennAktiv=3538;
    public static int PORTAL_sonstMitteilungenTextInOberflaecheLang=3539;
    public static int PORTAL_sonstMitteilungenTextInOberflaecheKurz=3840;

    public static int PORTAL_botschaftenStellerAbfragen=3860;
    public static int PORTAL_botschaftenNameAbfragen=3861;
    public static int PORTAL_botschaftenKontaktdatenAbfragen=3862;
    public static int PORTAL_botschaftenKontaktdatenEMailVorschlagen=3863;
    public static int PORTAL_botschaftenKontaktdatenTelefonAbfragen=3864;
    public static int PORTAL_botschaftenKurztextAbfragen=3865;
    public static int PORTAL_botschaftenTopListeAnbieten=3866;
    public static int PORTAL_botschaftenLangtextAbfragen=3867;
    public static int PORTAL_botschaftenLangtextUndDateiNurAlternativ=3868;
    public static int PORTAL_botschaftenZurueckziehenMoeglich=3869;
    public static int PORTAL_botschaftenAnzahlJeAktionaer=3870;
    public static int PORTAL_botschaftenStellerZulaessig=3871;
    public static int PORTAL_botschaftenMailBeiEingang=3872;
    public static int PORTAL_botschaftenMailVerteiler1=3873;
    public static int PORTAL_botschaftenMailVerteiler2=3874;
    public static int PORTAL_botschaftenMailVerteiler3=3875;
    public static int PORTAL_botschaftenHinweisVorbelegenMit=3876;
    public static int PORTAL_botschaftenHinweisGelesen=3877;
    public static int PORTAL_botschaftenZurueckziehenMoeglichNurWennAktiv=3878;
    public static int PORTAL_botschaftenVoranmeldungErforderlich=3879;
    
    public static int PORTAL_botschaftenVideo=3880;
    public static int PORTAL_botschaftenVideoFormate_1=3890;
    public static int PORTAL_botschaftenVideoFormate_2=3891;
    public static int PORTAL_botschaftenVideoFormate_3=3892;
    public static int PORTAL_botschaftenVideoFormate_4=3893;
    public static int PORTAL_botschaftenVideoFormate_5=3894;
    public static int PORTAL_botschaftenVideoFormate_6=3895;
    public static int PORTAL_botschaftenVideoFormate_7=3896;
    public static int PORTAL_botschaftenVideoFormate_8=3897;
    public static int PORTAL_botschaftenVideoFormate_9=3898;
    public static int PORTAL_botschaftenVideoFormate_10=3899;
    public static int PORTAL_botschaftenVideoFormate_11=3900;
    public static int PORTAL_botschaftenVideoFormate_12=3901;
    public static int PORTAL_botschaftenVideoFormate_13=3902;
    public static int PORTAL_botschaftenVideoFormate_14=3903;
    public static int PORTAL_botschaftenVideoFormate_15=3904;

    public static int PORTAL_botschaftenTextDatei=3910;
    public static int PORTAL_botschaftenTextFormate_1=3911;
    public static int PORTAL_botschaftenTextFormate_2=3912;
    public static int PORTAL_botschaftenTextFormate_3=3913;
    public static int PORTAL_botschaftenTextFormate_4=3914;
    public static int PORTAL_botschaftenTextFormate_5=3915;
    public static int PORTAL_botschaftenTextFormate_6=3916;
    public static int PORTAL_botschaftenTextFormate_7=3917;
    public static int PORTAL_botschaftenTextFormate_8=3918;
    public static int PORTAL_botschaftenTextFormate_9=3919;
    public static int PORTAL_botschaftenTextFormate_10=3920;
    public static int PORTAL_botschaftenTextFormate_11=3921;
    public static int PORTAL_botschaftenTextFormate_12=3922;
    public static int PORTAL_botschaftenTextFormate_13=3923;
    public static int PORTAL_botschaftenTextFormate_14=3924;
    public static int PORTAL_botschaftenTextFormate_15=3925;
    
    public static int PORTAL_botschaftenVideoLaenge=4000;
    public static int PORTAL_botschaftenTextDateiLaenge=4001;
    public static int PORTAL_botschaftenTextInOberflaecheLang=4002;
    public static int PORTAL_botschaftenTextInOberflaecheKurz=4003;

    public static int PORTAL_inhaltsHinweiseTextDE_1=4010;
    public static int PORTAL_inhaltsHinweiseTextDE_2=4011;
    public static int PORTAL_inhaltsHinweiseTextDE_3=4012;
    public static int PORTAL_inhaltsHinweiseTextDE_4=4013;
    public static int PORTAL_inhaltsHinweiseTextDE_5=4014;
    public static int PORTAL_inhaltsHinweiseTextDE_6=4015;
    public static int PORTAL_inhaltsHinweiseTextDE_7=4016;
    public static int PORTAL_inhaltsHinweiseTextDE_8=4017;
    public static int PORTAL_inhaltsHinweiseTextDE_9=4018;
    public static int PORTAL_inhaltsHinweiseTextDE_10=4019;

    public static int PORTAL_inhaltsHinweiseTextEN_1=4020;
    public static int PORTAL_inhaltsHinweiseTextEN_2=4021;
    public static int PORTAL_inhaltsHinweiseTextEN_3=4022;
    public static int PORTAL_inhaltsHinweiseTextEN_4=4023;
    public static int PORTAL_inhaltsHinweiseTextEN_5=4024;
    public static int PORTAL_inhaltsHinweiseTextEN_6=4025;
    public static int PORTAL_inhaltsHinweiseTextEN_7=4026;
    public static int PORTAL_inhaltsHinweiseTextEN_8=4027;
    public static int PORTAL_inhaltsHinweiseTextEN_9=4028;
    public static int PORTAL_inhaltsHinweiseTextEN_10=4029;

    
    public static int PORTAL_inhaltsHinweiseAktiv_1_Fragen=4031;
    public static int PORTAL_inhaltsHinweiseAktiv_2_Fragen=4032;
    public static int PORTAL_inhaltsHinweiseAktiv_3_Fragen=4033;
    public static int PORTAL_inhaltsHinweiseAktiv_4_Fragen=4034;
    public static int PORTAL_inhaltsHinweiseAktiv_5_Fragen=4035;
    public static int PORTAL_inhaltsHinweiseAktiv_6_Fragen=4036;
    public static int PORTAL_inhaltsHinweiseAktiv_7_Fragen=4037;
    public static int PORTAL_inhaltsHinweiseAktiv_8_Fragen=4038;
    public static int PORTAL_inhaltsHinweiseAktiv_9_Fragen=4039;
    public static int PORTAL_inhaltsHinweiseAktiv_10_Fragen=4040;
    
    public static int PORTAL_inhaltsHinweiseAktiv_1_Wortmeldungen=4041;
    public static int PORTAL_inhaltsHinweiseAktiv_2_Wortmeldungen=4042;
    public static int PORTAL_inhaltsHinweiseAktiv_3_Wortmeldungen=4043;
    public static int PORTAL_inhaltsHinweiseAktiv_4_Wortmeldungen=4044;
    public static int PORTAL_inhaltsHinweiseAktiv_5_Wortmeldungen=4045;
    public static int PORTAL_inhaltsHinweiseAktiv_6_Wortmeldungen=4046;
    public static int PORTAL_inhaltsHinweiseAktiv_7_Wortmeldungen=4047;
    public static int PORTAL_inhaltsHinweiseAktiv_8_Wortmeldungen=4048;
    public static int PORTAL_inhaltsHinweiseAktiv_9_Wortmeldungen=4049;
    public static int PORTAL_inhaltsHinweiseAktiv_10_Wortmeldungen=4050;
    
    public static int PORTAL_inhaltsHinweiseAktiv_1_Widerprueche=4051;
    public static int PORTAL_inhaltsHinweiseAktiv_2_Widerprueche=4052;
    public static int PORTAL_inhaltsHinweiseAktiv_3_Widerprueche=4053;
    public static int PORTAL_inhaltsHinweiseAktiv_4_Widerprueche=4054;
    public static int PORTAL_inhaltsHinweiseAktiv_5_Widerprueche=4055;
    public static int PORTAL_inhaltsHinweiseAktiv_6_Widerprueche=4056;
    public static int PORTAL_inhaltsHinweiseAktiv_7_Widerprueche=4057;
    public static int PORTAL_inhaltsHinweiseAktiv_8_Widerprueche=4058;
    public static int PORTAL_inhaltsHinweiseAktiv_9_Widerprueche=4059;
    public static int PORTAL_inhaltsHinweiseAktiv_10_Widerprueche=4060;
    
    public static int PORTAL_inhaltsHinweiseAktiv_1_Antraege=4061;
    public static int PORTAL_inhaltsHinweiseAktiv_2_Antraege=4062;
    public static int PORTAL_inhaltsHinweiseAktiv_3_Antraege=4063;
    public static int PORTAL_inhaltsHinweiseAktiv_4_Antraege=4064;
    public static int PORTAL_inhaltsHinweiseAktiv_5_Antraege=4065;
    public static int PORTAL_inhaltsHinweiseAktiv_6_Antraege=4066;
    public static int PORTAL_inhaltsHinweiseAktiv_7_Antraege=4067;
    public static int PORTAL_inhaltsHinweiseAktiv_8_Antraege=4068;
    public static int PORTAL_inhaltsHinweiseAktiv_9_Antraege=4069;
    public static int PORTAL_inhaltsHinweiseAktiv_10_Antraege=4070;
    
    public static int PORTAL_inhaltsHinweiseAktiv_1_SonstMitteil=4071;
    public static int PORTAL_inhaltsHinweiseAktiv_2_SonstMitteil=4072;
    public static int PORTAL_inhaltsHinweiseAktiv_3_SonstMitteil=4073;
    public static int PORTAL_inhaltsHinweiseAktiv_4_SonstMitteil=4074;
    public static int PORTAL_inhaltsHinweiseAktiv_5_SonstMitteil=4075;
    public static int PORTAL_inhaltsHinweiseAktiv_6_SonstMitteil=4076;
    public static int PORTAL_inhaltsHinweiseAktiv_7_SonstMitteil=4077;
    public static int PORTAL_inhaltsHinweiseAktiv_8_SonstMitteil=4078;
    public static int PORTAL_inhaltsHinweiseAktiv_9_SonstMitteil=4079;
    public static int PORTAL_inhaltsHinweiseAktiv_10_SonstMitteil=4080;

    public static int PORTAL_inhaltsHinweiseAktiv_1_Botschaften=4081;
    public static int PORTAL_inhaltsHinweiseAktiv_2_Botschaften=4082;
    public static int PORTAL_inhaltsHinweiseAktiv_3_Botschaften=4083;
    public static int PORTAL_inhaltsHinweiseAktiv_4_Botschaften=4084;
    public static int PORTAL_inhaltsHinweiseAktiv_5_Botschaften=4085;
    public static int PORTAL_inhaltsHinweiseAktiv_6_Botschaften=4086;
    public static int PORTAL_inhaltsHinweiseAktiv_7_Botschaften=4087;
    public static int PORTAL_inhaltsHinweiseAktiv_8_Botschaften=4088;
    public static int PORTAL_inhaltsHinweiseAktiv_9_Botschaften=4089;
    public static int PORTAL_inhaltsHinweiseAktiv_10_Botschaften=4090;

    public static int PORTAL_teilnehmerverzBeginnendBei=4101;
    public static int PORTAL_teilnehmerverzZusammenstellung=4102;
    public static int PORTAL_teilnehmerverzLetzteNr=4103;

    public static int PORTALabstimmungsergLetzteNr_=4104;

    public static int PORTAL_zuschaltungHVAutomatischNachLogin=4105;
    public static int PORTAL_zuschaltungHVStreamAutomatischStarten=4106;

    public static int PORTAL_kontaktformularAktiv=4107;
    public static int PORTAL_kontaktformularBeiEingangMail=4108;
    public static int PORTAL_kontaktformularBeiEingangMailAn=4109;
    public static int PORTAL_kontaktformularBeiEingangMailInhaltAufnehmen=4110;
    public static int PORTAL_kontaktformularBeiEingangAufgabe=4111;
    public static int PORTAL_kontaktformularAnzahlKontaktfelder=4112;
    public static int PORTAL_kontaktformularTelefonKontaktAbfragen=4113;
    public static int PORTAL_kontaktformularMailKontaktAbfragen=4114;
    public static int PORTAL_kontaktformularThemaAnbieten=4115;
    public static int PORTAL_kontaktformularThemenListeGlobalLokal=4116;
    public static int PORTAL_kontaktSonstigeMoeglichkeitenAnbieten=4117;
    public static int PORTAL_kontaktSonstigeMoeglichkeitenObenOderUnten=4118;

    public static int PORTAL_registerAnbindung=4119;
    public static int PORTAL_registerAnbindungOberflaeche=4120;
    public static int PORTAL_registerAnbindungCheckBeiLogin=4121;
    public static int PORTAL_registerAnbindungZurHV=4122;
    public static int PORTAL_registerAnbindungVonHV=4123;
    public static int PORTAL_api_client_id=4124;
    public static int PORTAL_api_client_secret=4125;
    public static int PORTAL_api_base_url=4126;
    public static int PORTAL_api_key_id=4127;
    public static int PORTAL_api_jwt_expiration_time=4128;
    public static int PORTAL_api_key_name=4129;
    public static int PORTAL_api_ping_url=4130;
    public static int PORTAL_apiku178_url=4131;
    
    public static int PORTAL_standardTexteBeruecksichtigen=4140;
    public static int PORTAL_basisSetStandardTexteVerwenden=4141;
    public static int PORTAL_fragezeichenHinweiseVerwenden=4142;
    
    public static int PORTAL_mehrereStimmrechtsvertreter=4145;
    public static int PORTAL_stimmrechtsvertreterNameDE=4146;
    public static int PORTAL_stimmrechtsvertreterNameEN=4147;
    public static int PORTAL_kurzLinkPortal=4148;
    public static int PORTAL_subdomainPortal=4149;
    public static int PORTAL_linkTagesordnung=4150;
    public static int PORTAL_linkGegenantraege=4151;
    public static int PORTAL_linkEinladungsPDF=4152;
    public static int PORTAL_linkNutzungsbedingungenAktionaersPortal=4153;
    public static int PORTAL_linkNutzungsbedingungenHVPortal=4154;
    public static int PORTAL_linkDatenschutzhinweise=4155;
    public static int PORTAL_linkDatenschutzhinweiseKunde=4156;
    public static int PORTAL_linkImpressum=4157;
    public static int PORTAL_emailAdresseLink=4158;
    public static int PORTAL_emailAdresseText=4159;
    public static int PORTAL_vollmachtEmailAdresseLink=4160;
    public static int PORTAL_vollmachtEmailAdresseText=4161;
    public static int PORTAL_ekText=4162;
    public static int PORTAL_ekTextMitArtikel=4163;
    public static int PORTAL_ekTextEN=4164;
    public static int PORTAL_ekTextENMitArtikel=4165;

    public static int PORTAL_logoutObenOderUnten=4180;
    public static int PORTAL_logoPosition=4181;
    public static int PORTAL_logoName=4182;
    public static int PORTAL_logoBreite=4183;
    public static int PORTAL_logoHoehe=4184;
    public static int PORTAL_cssName=4185;
    public static int PORTAL_designKuerzel=4186;

    public static int PORTAL_farbeHeader=4190;
    public static int PORTAL_farbeButton=4191;
    public static int PORTAL_farbeButtonHover=4192;
    public static int PORTAL_farbeButtonSchrift=4193;
    public static int PORTAL_farbeLink=4194;
    public static int PORTAL_farbeLinkHover=4195;
    public static int PORTAL_farbeListeUngerade=4196;
    public static int PORTAL_farbeListeGerade=4197;
    public static int PORTAL_farbeHintergrund=4198;
    public static int PORTAL_farbeText=4199;
    public static int PORTAL_farbeUeberschriftHintergrund=4200;
    public static int PORTAL_farbeUeberschrift=4201;

    public static int PORTAL_kachelFarbe=4210;
    public static int PORTAL_themeFarbe=4211;
    public static int PORTAL_schriftgroesseGlobal=4212;
    public static int PORTAL_logoMindestbreite=4213;
    public static int PORTAL_farbeHintergrundBtn00=4214;
    public static int PORTAL_farbeSchriftBtn00=4215;
    public static int PORTAL_farbeRahmenBtn00=4216;
    public static int PORTAL_breiteRahmenBtn00=4217;
    public static int PORTAL_radiusRahmenBtn00=4218;
    public static int PORTAL_stilRahmenBtn00=4219;
    public static int PORTAL_farbeHintergrundBtn00Hover=4220;
    public static int PORTAL_farbeSchriftBtn00Hover=4221;
    public static int PORTAL_farbeRahmenBtn00Hover=4222;
    public static int PORTAL_breiteRahmenBtn00Hover=4223;
    public static int PORTAL_radiusRahmenBtn00Hover=4224;
    public static int PORTAL_stilRahmenBtn00Hover=4225;
    public static int PORTAL_farbeFocus=4226;
    public static int PORTAL_farbeError=4227;
    public static int PORTAL_farbeErrorSchrift=4228;
    public static int PORTAL_farbeWarning=4229;
    public static int PORTAL_farbeWarningSchrift=4230;
    public static int PORTAL_farbeSuccess=4231;
    public static int PORTAL_farbeSuccessSchrift=4232;
    public static int PORTAL_farbeRahmenEingabefelder=4233;
    public static int PORTAL_breiteRahmenEingabefelder=4234;
    public static int PORTAL_radiusRahmenEingabefelder=4235;
    public static int PORTAL_stilRahmenEingabefelder=4236;
    public static int PORTAL_farbeHintergrundLogoutBtn=4237;
    public static int PORTAL_farbeSchriftLogoutBtn=4238;
    public static int PORTAL_farbeRahmenLogoutBtn=4239;
    public static int PORTAL_breiteRahmenLogoutBtn=4240;
    public static int PORTAL_radiusRahmenLogoutBtn=4241;
    public static int PORTAL_stilRahmenLogoutBtn=4242;
    public static int PORTAL_farbeHintergrundLogoutBtnHover=4243;
    public static int PORTAL_farbeSchriftLogoutBtnHover=4244;
    public static int PORTAL_farbeRahmenLogoutBtnHover=4245;
    public static int PORTAL_breiteRahmenLogoutBtnHover=4246;
    public static int PORTAL_radiusRahmenLogoutBtnHover=4247;
    public static int PORTAL_stilRahmenLogoutBtnHover=4248;
    public static int PORTAL_farbeHintergrundLoginBtn=4249;
    public static int PORTAL_farbeSchriftLoginBtn=4250;
    public static int PORTAL_farbeRahmenLoginBtn=4251;
    public static int PORTAL_breiteRahmenLoginBtn=4252;
    
    public static int PORTAL_radiusRahmenLoginBtn=4255;
    public static int PORTAL_stilRahmenLoginBtn=4256;
    public static int PORTAL_farbeHintergrundLoginBtnHover=4257;
    public static int PORTAL_farbeSchriftLoginBtnHover=4258;
    public static int PORTAL_farbeRahmenLoginBtnHover=4259;
    public static int PORTAL_breiteRahmenLoginBtnHover=4260;
    public static int PORTAL_radiusRahmenLoginBtnHover=4261;
    public static int PORTAL_stilRahmenLoginBtnHover=4262;
    public static int PORTAL_farbeRahmenLoginBereich=4263;
    public static int PORTAL_breiteRahmenLoginBereich=4264;
    public static int PORTAL_radiusRahmenLoginBereich=4265;
    public static int PORTAL_stilRahmenLoginBereich=4266;
    public static int PORTAL_farbeHintergrundLoginBereich=4267;
    public static int PORTAL_farbeLinkLoginBereich=4268;
    public static int PORTAL_farbeLinkHoverLoginBereich=4269;
    public static int PORTAL_farbeRahmenEingabefelderLoginBereich=4270;
    public static int PORTAL_breiteRahmenEingabefelderLoginBereich=4271;
    
    public static int PORTAL_radiusRahmenEingabefelderLoginBereich=4275;
    public static int PORTAL_stilRahmenEingabefelderLoginBereich=4276;
    public static int PORTAL_farbeBestandsbereichUngeradeReihe=4277;
    public static int PORTAL_farbeBestandsbereichGeradeReihe=4278;
    public static int PORTAL_farbeLineUntenBestandsbereich=4279;
    public static int PORTAL_breiteLineUntenBestandsbereich=4280;
    public static int PORTAL_stilLineUntenBestandsbereich=4281;
    public static int PORTAL_farbeRahmenAnmeldeuebersicht=4282;
    public static int PORTAL_breiteRahmenAnmeldeuebersicht=4283;
    public static int PORTAL_radiusRahmenAnmeldeuebersicht=4284;
    public static int PORTAL_stilRahmenAnmeldeuebersicht=4285;
    public static int PORTAL_farbeTrennlinieAnmeldeuebersicht=4286;
    public static int PORTAL_breiteTrennlinieAnmeldeuebersicht=4287;
    public static int PORTAL_stilTrennlinieAnmeldeuebersicht=4288;
    public static int PORTAL_farbeRahmenErteilteWillenserklärungen=4289;
    public static int PORTAL_breiteRahmenErteilteWillenserklärungen=4290;
    public static int PORTAL_radiusRahmenErteilteWillenserklärungen=4291;
    public static int PORTAL_stilRahmenErteilteWillenserklärungen=4292;
    public static int PORTAL_farbeHintergrundErteilteWillenserklärungen=4293;
    public static int PORTAL_farbeSchriftErteilteWillenserklärungen=4294;

    public static int PORTAL_farbeRahmenAbstimmungstabelle=4300;
    public static int PORTAL_breiteRahmenAbstimmungstabelle=4301;
    public static int PORTAL_radiusRahmenAbstimmungstabelle=4302;
    public static int PORTAL_stilRahmenAbstimmungstabelle=4303;
    public static int PORTAL_farbeHintergrundAbstimmungstabelleUngeradeReihen=4304;
    public static int PORTAL_farbeSchriftAbstimmungstabelleUngeradeReihen=4305;
    public static int PORTAL_farbeHintergrundAbstimmungstabelleGeradeReihen=4306;
    public static int PORTAL_farbeSchriftAbstimmungstabelleGeradeReihen=4307;
    public static int PORTAL_farbeHintergrundWeisungJa=4308;
    public static int PORTAL_farbeSchriftWeisungJa=4309;
    public static int PORTAL_farbeRahmenWeisungJa=4310;
    public static int PORTAL_farbeHintergrundWeisungJaChecked=4311;
    public static int PORTAL_farbeSchriftWeisungJaChecked=4312;
    public static int PORTAL_farbeRahmenWeisungJaChecked=4313;
    public static int PORTAL_farbeHintergrundWeisungNein=4314;
    public static int PORTAL_farbeSchriftWeisungNein=4315;
    public static int PORTAL_farbeRahmenWeisungNein=4316;
    public static int PORTAL_farbeHintergrundWeisungNeinChecked=4317;
    public static int PORTAL_farbeSchriftWeisungNeinChecked=4318;
    public static int PORTAL_farbeRahmenWeisungNeinChecked=4319;
    public static int PORTAL_farbeHintergrundWeisungEnthaltung=4320;
    public static int PORTAL_farbeSchriftWeisungEnthaltung=4321;
    public static int PORTAL_farbeRahmenWeisungEnthaltung=4322;
    public static int PORTAL_farbeHintergrundWeisungEnthaltungChecked=4323;
    public static int PORTAL_farbeSchriftWeisungEnthaltungChecked=4324;
    public static int PORTAL_farbeRahmenWeisungEnthaltungChecked=4325;
    
    public static int PORTAL_farbeHintergrundFooterTop=4326;
    public static int PORTAL_farbeSchriftFooterTop=4327;
    public static int PORTAL_farbeLinkFooterTop=4328;
    public static int PORTAL_farbeLinkFooterTopHover=4329;
    public static int PORTAL_farbeHintergrundFooterBottom=4330;
    public static int PORTAL_farbeSchriftFooterBottom=4331;
    public static int PORTAL_farbeLinkFooterBottom=4332;
    public static int PORTAL_farbeLinkFooterBottomHover=4333;
    public static int PORTAL_farbeHintergrundModal=4334;
    public static int PORTAL_farbeSchriftModal=4335;
    public static int PORTAL_farbeHintergrundModalHeader=4336;
    public static int PORTAL_farbeSchriftModalHeader=4337;
    public static int PORTAL_farbeTrennlinieModal=4338;
    public static int PORTAL_farbeHintergrundUntenButtons=4339;
    public static int PORTAL_farbeSchriftUntenButtons=4340;
    public static int PORTAL_farbeRahmenUntenButtons=4341;
    public static int PORTAL_breiteRahmenUntenButtons=4342;
    public static int PORTAL_radiusRahmenUntenButtons=4343;
    public static int PORTAL_stilRahmenUntenButtons=4344;
    public static int PORTAL_farbeHintergrundUntenButtonsHover=4345;

    public static int PORTAL_farbeRahmenUntenButtonsHover=4350;
    public static int PORTAL_breiteRahmenUntenButtonsHover=4351;
    public static int PORTAL_radiusRahmenUntenButtonsHover=4352;
    public static int PORTAL_stilRahmenUntenButtonsHover=4353;
    public static int PORTAL_farbeCookieHintHintergrund=4354;
    public static int PORTAL_farbeCookieHintSchrift=4355;
    public static int PORTAL_farbeCookieHintButton=4356;
    public static int PORTAL_farbeCookieHintButtonSchrift=4357;
    public static int PORTAL_farbeLadebalkenUploadLeer=4358;
    public static int PORTAL_farbeLadebalkenUploadFull=4359;

    public static int PORTAL_SERVER_appInstallButtonsAnzeigen=4400;
    public static int PORTAL_SERVER_httpPfadTeil1=4401;
    public static int PORTAL_SERVER_httpPfadTeil2=4402;

    
    /*eclPortalFunktion, eclPortalPhase
     * kontaktformularThemenListe
     * 
     * ParamPortalServer:
     * phasenNamen*/
    
    
//    public static int BASIS__=;
//  public static int PORTAL_SERVER_=;
    
    /**Parameter, die nicht über diesen Mechanismus bearbeitet werden dürfen*/
    public static int BASIS__VERANSTALTUNGSTYP=1000001;
    public static int BASIS__P_LOCAL_VERZOEGERUNG_OPEN=1000002;
    public static int BASIS__AUTO_DRUCKER_VERWENDUNG_X=1000003;

    /**Dummmy-Parameter*/
    public static int AKKREDITIERUNG_SK_OFFENLEGUNG_BRIEFWAHL=1100001;

}
